services:
  person_service:
    image: person_service
    build:
      context: ../
      dockerfile: src/Services/PersonService/PersonService.Infrastructure/PersonService.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${PERSON_SERVICE_CONNECTION_STRING}
    depends_on:
      - postgres
    restart: on-failure:10
    networks:
      - movie_hub
    ports:
      - ${PERSON_SERVICE_PORT}:80
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - movie_hub
    ports:
      - ${POSTGRES_PORT}:5432

networks:
  movie_hub: